# Generated by Django 2.2.2 on 2019-06-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGS_in_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordno', models.CharField(max_length=12)),
                ('name_fullname', models.TextField()),
                ('family_number', models.TextField()),
                ('team', models.TextField()),
                ('disease', models.TextField()),
                ('profile', models.TextField()),
                ('urg', models.BooleanField()),
                ('received', models.DateField()),
                ('activated', models.DateField()),
                ('fragmentation', models.DateField()),
                ('fragmentation_batch', models.CharField(max_length=7)),
                ('library_prep', models.DateField()),
                ('library_prep_batch', models.CharField(max_length=7)),
                ('library_completion', models.DateField()),
                ('library_completion_batch', models.CharField(max_length=7)),
                ('reporting', models.DateField()),
                ('reporting_batch', models.CharField(max_length=7)),
                ('report_generated', models.DateField()),
                ('status', models.CharField(max_length=6)),
            ],
        ),
    ]
