# Generated by Django 2.2.2 on 2019-06-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MI_data', '0003_auto_20190623_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='activated',
            field=models.DateField(verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='disease',
            field=models.TextField(verbose_name='Investigation'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='family_number',
            field=models.TextField(verbose_name='Family number'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='fragmentation',
            field=models.DateField(verbose_name='Fragmentation date'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='fragmentation_batch',
            field=models.CharField(max_length=7, verbose_name='Fragmentation batch'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='library_completion',
            field=models.DateField(verbose_name='Library completion date'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='library_completion_batch',
            field=models.CharField(max_length=7, verbose_name='Library completion batch'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='library_prep',
            field=models.DateField(verbose_name='Library prep date'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='library_prep_batch',
            field=models.CharField(max_length=7, verbose_name='Library prep batch'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='name_fullname',
            field=models.TextField(verbose_name='Patient name'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='profile',
            field=models.TextField(verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='received',
            field=models.DateField(verbose_name='Received'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='report_generated',
            field=models.DateField(verbose_name='Report Generation date'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='reporting',
            field=models.DateField(verbose_name='Reporting batch date'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='reporting_batch',
            field=models.CharField(max_length=7, verbose_name='Reporting batch'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='status',
            field=models.CharField(max_length=6, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='team',
            field=models.TextField(verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='ngs_in_progress',
            name='urg',
            field=models.BooleanField(verbose_name='Urgent?'),
        ),
    ]
